# Generated by Django 3.0.8 on 2021-01-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='index',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
