# Generated by Django 3.1.2 on 2021-03-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0002_player_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='allegiance',
            field=models.CharField(default='Billiam', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='stat',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(default='beep boop', max_length=100),
        ),
    ]
