# Generated by Django 3.1.2 on 2021-05-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0006_draft_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft_started',
            name='draftStarted',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
