# Generated by Django 3.1.2 on 2021-05-15 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0007_auto_20210515_0128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='draft_started',
        ),
    ]
