# Generated by Django 3.0.8 on 2021-05-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0008_delete_draft_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='index',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
